---
- name: Check installation
  shell: 'test -f {{ zookeeper_path }}/bin/zkServer.sh && echo "yes" || echo "no"'
  changed_when: false
  register: installed_status

- name: Get installed version
  shell: readlink -f {{ zookeeper_path }} | sed -nr 's/.*zookeeper\-(.*)/\1/p'
  when: installed_status.stdout == "yes"
  register: installed_version

- name: Set installed variable
  set_fact: is_installed='{{ installed_status.stdout == "yes" and installed_version.stdout == zookeeper.version }}'

- name: Add dependencies repository
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes

- name: Set dependencies License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  changed_when: false

- name: Install Dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - oracle-java8-installer
    - make

- name: Create User
  user: name={{ zookeeper_user }} system=yes shell=/bin/bash

- name: Discover the closest mirror for Apache ZooKeeper
  shell: curl -s {{ zookeeper_discover_url }} | sed -n '/id="http"/,/id="backup"/p' | sed -nr 's/.*href=\"(.*)\".*/\1/p' | sed -n 2p
  register: zookeeper_mirror_url
  when: not is_installed

- name: Set source url
  set_fact: zookeeper_source="{{ zookeeper_mirror_url.stdout }}/{{zookeeper_filename}}/{{ zookeeper_filename }}{{ zookeeper_filename_extension }}"
  when: not is_installed

- name: Download
  get_url: url={{ zookeeper_source }} dest=/tmp
  when: not is_installed

- name: Unarchive
  unarchive: >
    src=/tmp/{{ zookeeper_filename }}{{ zookeeper_filename_extension }}
    dest=/opt
    copy=no
  when: not is_installed

- name: Apply permissions into unarchived file
  file: >
    path=/opt/{{ zookeeper_filename }}
    owner={{ zookeeper_user }}
    recurse=yes

- name: Link folder
  file: >
    src=/opt/{{ zookeeper_filename }}
    dest={{ zookeeper_path }}
    owner={{ zookeeper_user }}
    state=link

- name: Create /var folders
  file: path={{ item }} state=directory
  with_items:
    - "{{ zookeeper_var_path }}"
    - "{{ zookeeper_var_path }}/data"
    - "/var/log/zookeeper"

- name: Create config file
  command: "cp {{ zookeeper_path }}/conf/zoo_sample.cfg {{ zookeeper_var_path }}/zoo.cfg"
  when: not is_installed

- name: Set config file parameters
  replace: >
    dest="{{ zookeeper_var_path }}/zoo.cfg"
    regexp="{{ item.regexp }}"
    replace="{{ item.replace }}"
  with_items:
    - { regexp: '^(dataDir=).*', replace: '\1{{ zookeeper_var_path }}/data'}
    - { regexp: '^(clientPort).*', replace: '\1={{ zookeeper.port }}'}
  when: not is_installed

- name: Set path into script file
  lineinfile: >
    dest={{ zookeeper_path }}/bin/zkServer.sh
    regexp="^ZOOBIN="
    line='ZOOBIN="{{ zookeeper_path }}/bin"'

- name: Set config path into script file
  lineinfile: >
    dest="{{ zookeeper_path }}/bin/zkServer.sh"
    insertafter="^ZOOBINDIR=.*"
    line='ZOOCFGDIR="{{ zookeeper_var_path }}"'

- name: Apply permission into /var/solr
  file: >
    path={{ item }}
    owner={{ zookeeper_user }}
    group={{ zookeeper_user }}
    state=directory
    recurse=yes
  with_items:
    - "{{ zookeeper_var_path }}"
    - "/var/log/zookeeper"

- name: Set start script
  template: >
    src=init.tpl
    dest=/etc/init.d/zookeeper
    owner=root
    group=root
    mode=0744

- name: Register service
  service: name=zookeeper enabled=yes

- name: Flush handlers to apply config changes
  meta: flush_handlers

- name: Ensure ZooKeeper is started
  service: name=zookeeper state=started

- name: Remove tmp files
  file: path=/tmp/{{ zookeeper_filename }}{{ zookeeper_filename_extension }} state=absent

- name: Check library
  shell: 'test -f /usr/local/include/zookeeper/zookeeper.h && echo "yes" || echo "no"'
  changed_when: false
  register: library_status

- name: Configure library
  command: ./configure chdir={{ zookeeper_path }}/src/c
  when: library_status.stdout == "no"

- name: Build library
  command: make chdir={{ zookeeper_path }}/src/c
  when: library_status.stdout == "no"

- name: Install library
  command: make install chdir={{ zookeeper_path }}/src/c
  when: library_status.stdout == "no"
